SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Altering [dbo].[Posts]'
GO
ALTER TABLE [dbo].[Posts] ADD
[twitter_id] [nvarchar] (20) NULL
GO
